### ISSUE TITLE
Error in xcode 7

### ISSUE THREAD

**Issue by moh1122** [MoZhouqi/VoiceMemos#2]
Hello 
while building on xcode 7 an error occurred: 
No such module 'KMPlaceholderTextView'
any clue ?

**Comment by MoZhouqi** [comment]
Hi, could you try to open VoiceMemos.xcworkspace?

**Comment by moh1122** [comment]
thnks mozhouqi its working now
btw i tried recoarding in backgraound and it works well but as soon as i play music it stops rec 
any clue do u think there is a way to fix it

**Comment by MoZhouqi** [comment]
Yes, you could not record and play at the same time.

**Comment by moh1122** [comment]
is there a work around for this it wont work at all?

**Comment by MoZhouqi** [comment]
You could try to change the recording and playback logic, and set the category of `AVAudioSession.sharedInstance()` to be `AVAudioSessionCategoryPlayAndRecord`.
